/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'sku' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'lastUpdated' : Time,
  'category' : IDL.Text,
  'unitPrice' : IDL.Float64,
});
export const SalesProduct = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'amount' : IDL.Float64,
});
export const SalesRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'date' : Time,
  'agentName' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'paymentMode' : IDL.Text,
  'agentMobile' : IDL.Text,
  'products' : IDL.Vec(SalesProduct),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'dispatched' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'createdAt' : Time,
  'agentName' : IDL.Text,
  'customerMobile' : IDL.Text,
  'updatedAt' : Time,
  'totalAmount' : IDL.Float64,
  'items' : IDL.Vec(OrderItem),
  'agentMobile' : IDL.Text,
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'closed' : IDL.Null,
    'in_progress' : IDL.Null,
    'open' : IDL.Null,
  }),
  'assignedAgentName' : IDL.Text,
  'assignedAgentMobile' : IDL.Text,
  'createdAt' : Time,
  'customerMobile' : IDL.Text,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const AgentLocation = IDL.Record({
  'territory' : IDL.Text,
  'agentName' : IDL.Text,
  'isActive' : IDL.Bool,
  'lastCheckIn' : Time,
  'agentMobile' : IDL.Text,
  'locationName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [Product],
      [],
    ),
  'addSalesRecord' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        Time,
        IDL.Vec(SalesProduct),
        IDL.Float64,
        IDL.Text,
      ],
      [SalesRecord],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(OrderItem), IDL.Float64],
      [Order],
      [],
    ),
  'createServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ServiceRequest],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getActiveAgents' : IDL.Func([], [IDL.Vec(AgentLocation)], ['query']),
  'getAgentLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(AgentLocation)],
      ['query'],
    ),
  'getAgentLocations' : IDL.Func([], [IDL.Vec(AgentLocation)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOpenServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getOrderStatsByStatus' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByAgent' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getOrdersByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'dispatched' : IDL.Null,
          'delivered' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getSalesRecordStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
  'getSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
  'getSalesRecordsByAgent' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SalesRecord)],
      ['query'],
    ),
  'getSalesRecordsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(SalesRecord)],
      ['query'],
    ),
  'getSalesSummaryByProduct' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
      ['query'],
    ),
  'getServiceRequest' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ServiceRequest)],
      ['query'],
    ),
  'getServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getTotalInventoryValue' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalOrders' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'updateAgentLocation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [AgentLocation],
      [],
    ),
  'updateOrderStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'pending' : IDL.Null,
          'dispatched' : IDL.Null,
          'delivered' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [IDL.Opt(Order)],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Opt(Product)],
      [],
    ),
  'updateServiceRequest' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'closed' : IDL.Null,
          'in_progress' : IDL.Null,
          'open' : IDL.Null,
        }),
      ],
      [IDL.Opt(ServiceRequest)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'sku' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'lastUpdated' : Time,
    'category' : IDL.Text,
    'unitPrice' : IDL.Float64,
  });
  const SalesProduct = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'amount' : IDL.Float64,
  });
  const SalesRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'date' : Time,
    'agentName' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'paymentMode' : IDL.Text,
    'agentMobile' : IDL.Text,
    'products' : IDL.Vec(SalesProduct),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'dispatched' : IDL.Null,
      'delivered' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'createdAt' : Time,
    'agentName' : IDL.Text,
    'customerMobile' : IDL.Text,
    'updatedAt' : Time,
    'totalAmount' : IDL.Float64,
    'items' : IDL.Vec(OrderItem),
    'agentMobile' : IDL.Text,
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'closed' : IDL.Null,
      'in_progress' : IDL.Null,
      'open' : IDL.Null,
    }),
    'assignedAgentName' : IDL.Text,
    'assignedAgentMobile' : IDL.Text,
    'createdAt' : Time,
    'customerMobile' : IDL.Text,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const AgentLocation = IDL.Record({
    'territory' : IDL.Text,
    'agentName' : IDL.Text,
    'isActive' : IDL.Bool,
    'lastCheckIn' : Time,
    'agentMobile' : IDL.Text,
    'locationName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [Product],
        [],
      ),
    'addSalesRecord' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          Time,
          IDL.Vec(SalesProduct),
          IDL.Float64,
          IDL.Text,
        ],
        [SalesRecord],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(OrderItem),
          IDL.Float64,
        ],
        [Order],
        [],
      ),
    'createServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ServiceRequest],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getActiveAgents' : IDL.Func([], [IDL.Vec(AgentLocation)], ['query']),
    'getAgentLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(AgentLocation)],
        ['query'],
      ),
    'getAgentLocations' : IDL.Func([], [IDL.Vec(AgentLocation)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOpenServiceRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getOrderStatsByStatus' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByAgent' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getOrdersByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'dispatched' : IDL.Null,
            'delivered' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getSalesRecordStats' : IDL.Func([], [IDL.Nat, IDL.Float64], ['query']),
    'getSalesRecords' : IDL.Func([], [IDL.Vec(SalesRecord)], ['query']),
    'getSalesRecordsByAgent' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SalesRecord)],
        ['query'],
      ),
    'getSalesRecordsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(SalesRecord)],
        ['query'],
      ),
    'getSalesSummaryByProduct' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat, IDL.Float64))],
        ['query'],
      ),
    'getServiceRequest' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ServiceRequest)],
        ['query'],
      ),
    'getServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getTotalInventoryValue' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalOrders' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'updateAgentLocation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [AgentLocation],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'pending' : IDL.Null,
            'dispatched' : IDL.Null,
            'delivered' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Opt(Product)],
        [],
      ),
    'updateServiceRequest' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'closed' : IDL.Null,
            'in_progress' : IDL.Null,
            'open' : IDL.Null,
          }),
        ],
        [IDL.Opt(ServiceRequest)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };