/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgentLocation {
  'territory' : string,
  'agentName' : string,
  'isActive' : boolean,
  'lastCheckIn' : Time,
  'agentMobile' : string,
  'locationName' : string,
}
export interface Order {
  'id' : bigint,
  'customerName' : string,
  'status' : { 'pending' : null } |
    { 'dispatched' : null } |
    { 'delivered' : null } |
    { 'confirmed' : null },
  'createdAt' : Time,
  'agentName' : string,
  'customerMobile' : string,
  'updatedAt' : Time,
  'totalAmount' : number,
  'items' : Array<OrderItem>,
  'agentMobile' : string,
}
export interface OrderItem {
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : number,
}
export interface Product {
  'id' : bigint,
  'sku' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'lastUpdated' : Time,
  'category' : string,
  'unitPrice' : number,
}
export interface SalesProduct {
  'productName' : string,
  'quantity' : bigint,
  'amount' : number,
}
export interface SalesRecord {
  'id' : bigint,
  'customerName' : string,
  'date' : Time,
  'agentName' : string,
  'totalAmount' : number,
  'paymentMode' : string,
  'agentMobile' : string,
  'products' : Array<SalesProduct>,
}
export interface ServiceRequest {
  'id' : bigint,
  'customerName' : string,
  'status' : { 'closed' : null } |
    { 'in_progress' : null } |
    { 'open' : null },
  'assignedAgentName' : string,
  'assignedAgentMobile' : string,
  'createdAt' : Time,
  'customerMobile' : string,
  'description' : string,
  'updatedAt' : Time,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[string, string, string, bigint, number], Product>,
  'addSalesRecord' : ActorMethod<
    [string, string, string, Time, Array<SalesProduct>, number, string],
    SalesRecord
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'createOrder' : ActorMethod<
    [string, string, string, string, Array<OrderItem>, number],
    Order
  >,
  'createServiceRequest' : ActorMethod<
    [string, string, string, string, string],
    ServiceRequest
  >,
  'deleteProduct' : ActorMethod<[bigint], boolean>,
  'getActiveAgents' : ActorMethod<[], Array<AgentLocation>>,
  'getAgentLocation' : ActorMethod<[string], [] | [AgentLocation]>,
  'getAgentLocations' : ActorMethod<[], Array<AgentLocation>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOpenServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getOrderStatsByStatus' : ActorMethod<[], [bigint, bigint, bigint, bigint]>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByAgent' : ActorMethod<[string], Array<Order>>,
  'getOrdersByStatus' : ActorMethod<
    [
      { 'pending' : null } |
        { 'dispatched' : null } |
        { 'delivered' : null } |
        { 'confirmed' : null },
    ],
    Array<Order>
  >,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getSalesRecordStats' : ActorMethod<[], [bigint, number]>,
  'getSalesRecords' : ActorMethod<[], Array<SalesRecord>>,
  'getSalesRecordsByAgent' : ActorMethod<[string], Array<SalesRecord>>,
  'getSalesRecordsByDateRange' : ActorMethod<[Time, Time], Array<SalesRecord>>,
  'getSalesSummaryByProduct' : ActorMethod<[], Array<[string, bigint, number]>>,
  'getServiceRequest' : ActorMethod<[bigint], [] | [ServiceRequest]>,
  'getServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getTotalInventoryValue' : ActorMethod<[], number>,
  'getTotalOrderCount' : ActorMethod<[], bigint>,
  'getTotalOrders' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'updateAgentLocation' : ActorMethod<
    [string, string, string, string, boolean],
    AgentLocation
  >,
  'updateOrderStatus' : ActorMethod<
    [
      bigint,
      { 'pending' : null } |
        { 'dispatched' : null } |
        { 'delivered' : null } |
        { 'confirmed' : null },
    ],
    [] | [Order]
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, string, string, bigint, number],
    [] | [Product]
  >,
  'updateServiceRequest' : ActorMethod<
    [
      bigint,
      { 'closed' : null } |
        { 'in_progress' : null } |
        { 'open' : null },
    ],
    [] | [ServiceRequest]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];