/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceRequest {
    id: bigint;
    customerName: string;
    status: Variant_closed_in_progress_open;
    assignedAgentName: string;
    assignedAgentMobile: string;
    createdAt: Time;
    customerMobile: string;
    description: string;
    updatedAt: Time;
}
export type Time = bigint;
export interface SalesProduct {
    productName: string;
    quantity: bigint;
    amount: number;
}
export interface OrderItem {
    productName: string;
    quantity: bigint;
    unitPrice: number;
}
export interface SalesRecord {
    id: bigint;
    customerName: string;
    date: Time;
    agentName: string;
    totalAmount: number;
    paymentMode: string;
    agentMobile: string;
    products: Array<SalesProduct>;
}
export interface Order {
    id: bigint;
    customerName: string;
    status: Variant_pending_dispatched_delivered_confirmed;
    createdAt: Time;
    agentName: string;
    customerMobile: string;
    updatedAt: Time;
    totalAmount: number;
    items: Array<OrderItem>;
    agentMobile: string;
}
export interface Product {
    id: bigint;
    sku: string;
    stockQuantity: bigint;
    name: string;
    lastUpdated: Time;
    category: string;
    unitPrice: number;
}
export interface AgentLocation {
    territory: string;
    agentName: string;
    isActive: boolean;
    lastCheckIn: Time;
    agentMobile: string;
    locationName: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_closed_in_progress_open {
    closed = "closed",
    in_progress = "in_progress",
    open = "open"
}
export enum Variant_pending_dispatched_delivered_confirmed {
    pending = "pending",
    dispatched = "dispatched",
    delivered = "delivered",
    confirmed = "confirmed"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(name: string, sku: string, category: string, stockQuantity: bigint, unitPrice: number): Promise<Product>;
    addSalesRecord(agentMobile: string, agentName: string, customerName: string, date: Time, products: Array<SalesProduct>, totalAmount: number, paymentMode: string): Promise<SalesRecord>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelOrder(id: bigint): Promise<boolean>;
    createOrder(agentMobile: string, agentName: string, customerName: string, customerMobile: string, items: Array<OrderItem>, totalAmount: number): Promise<Order>;
    createServiceRequest(customerName: string, customerMobile: string, description: string, assignedAgentMobile: string, assignedAgentName: string): Promise<ServiceRequest>;
    deleteProduct(id: bigint): Promise<boolean>;
    getActiveAgents(): Promise<Array<AgentLocation>>;
    getAgentLocation(agentMobile: string): Promise<AgentLocation | null>;
    getAgentLocations(): Promise<Array<AgentLocation>>;
    getCallerUserRole(): Promise<UserRole>;
    getOpenServiceRequests(): Promise<Array<ServiceRequest>>;
    getOrder(id: bigint): Promise<Order | null>;
    getOrderStatsByStatus(): Promise<[bigint, bigint, bigint, bigint]>;
    getOrders(): Promise<Array<Order>>;
    getOrdersByAgent(agentMobile: string): Promise<Array<Order>>;
    getOrdersByStatus(status: Variant_pending_dispatched_delivered_confirmed): Promise<Array<Order>>;
    getProduct(id: bigint): Promise<Product | null>;
    getProducts(): Promise<Array<Product>>;
    getSalesRecordStats(): Promise<[bigint, number]>;
    getSalesRecords(): Promise<Array<SalesRecord>>;
    getSalesRecordsByAgent(agentMobile: string): Promise<Array<SalesRecord>>;
    getSalesRecordsByDateRange(startDate: Time, endDate: Time): Promise<Array<SalesRecord>>;
    getSalesSummaryByProduct(): Promise<Array<[string, bigint, number]>>;
    getServiceRequest(id: bigint): Promise<ServiceRequest | null>;
    getServiceRequests(): Promise<Array<ServiceRequest>>;
    getTotalInventoryValue(): Promise<number>;
    getTotalOrderCount(): Promise<bigint>;
    getTotalOrders(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    updateAgentLocation(agentMobile: string, agentName: string, territory: string, locationName: string, isActive: boolean): Promise<AgentLocation>;
    updateOrderStatus(id: bigint, status: Variant_pending_dispatched_delivered_confirmed): Promise<Order | null>;
    updateProduct(id: bigint, name: string, sku: string, category: string, stockQuantity: bigint, unitPrice: number): Promise<Product | null>;
    updateServiceRequest(id: bigint, status: Variant_closed_in_progress_open): Promise<ServiceRequest | null>;
}
import type { AgentLocation as _AgentLocation, Order as _Order, OrderItem as _OrderItem, Product as _Product, ServiceRequest as _ServiceRequest, Time as _Time, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: number): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async addSalesRecord(arg0: string, arg1: string, arg2: string, arg3: Time, arg4: Array<SalesProduct>, arg5: number, arg6: string): Promise<SalesRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.addSalesRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSalesRecord(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<OrderItem>, arg5: number): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_Order_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createServiceRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<ServiceRequest> {
        if (this.processError) {
            try {
                const result = await this.actor.createServiceRequest(arg0, arg1, arg2, arg3, arg4);
                return from_candid_ServiceRequest_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServiceRequest(arg0, arg1, arg2, arg3, arg4);
            return from_candid_ServiceRequest_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getActiveAgents(): Promise<Array<AgentLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveAgents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveAgents();
            return result;
        }
    }
    async getAgentLocation(arg0: string): Promise<AgentLocation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLocation(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLocation(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAgentLocations(): Promise<Array<AgentLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgentLocations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgentLocations();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenServiceRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenServiceRequests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenServiceRequests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: bigint): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStatsByStatus(): Promise<[bigint, bigint, bigint, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatsByStatus();
                return [
                    result[0],
                    result[1],
                    result[2],
                    result[3]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatsByStatus();
            return [
                result[0],
                result[1],
                result[2],
                result[3]
            ];
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByAgent(arg0: string): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByAgent(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByAgent(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrdersByStatus(arg0: Variant_pending_dispatched_delivered_confirmed): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrdersByStatus(to_candid_variant_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrdersByStatus(to_candid_variant_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return result;
        }
    }
    async getSalesRecordStats(): Promise<[bigint, number]> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecordStats();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecordStats();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getSalesRecords(): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecords();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecords();
            return result;
        }
    }
    async getSalesRecordsByAgent(arg0: string): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecordsByAgent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecordsByAgent(arg0);
            return result;
        }
    }
    async getSalesRecordsByDateRange(arg0: Time, arg1: Time): Promise<Array<SalesRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesRecordsByDateRange(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesRecordsByDateRange(arg0, arg1);
            return result;
        }
    }
    async getSalesSummaryByProduct(): Promise<Array<[string, bigint, number]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSalesSummaryByProduct();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSalesSummaryByProduct();
            return result;
        }
    }
    async getServiceRequest(arg0: bigint): Promise<ServiceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceRequest(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceRequest(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceRequests();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceRequests();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalInventoryValue(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalInventoryValue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalInventoryValue();
            return result;
        }
    }
    async getTotalOrderCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalOrderCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalOrderCount();
            return result;
        }
    }
    async getTotalOrders(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalOrders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalOrders();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async updateAgentLocation(arg0: string, arg1: string, arg2: string, arg3: string, arg4: boolean): Promise<AgentLocation> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAgentLocation(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAgentLocation(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: Variant_pending_dispatched_delivered_confirmed): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_variant_n15(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: number): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateServiceRequest(arg0: bigint, arg1: Variant_closed_in_progress_open): Promise<ServiceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceRequest(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceRequest(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Order_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRequest_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRequest): ServiceRequest {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n3(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceRequest]): ServiceRequest | null {
    return value.length === 0 ? null : from_candid_ServiceRequest_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AgentLocation]): AgentLocation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: {
        pending: null;
    } | {
        dispatched: null;
    } | {
        delivered: null;
    } | {
        confirmed: null;
    };
    createdAt: _Time;
    agentName: string;
    customerMobile: string;
    updatedAt: _Time;
    totalAmount: number;
    items: Array<_OrderItem>;
    agentMobile: string;
}): {
    id: bigint;
    customerName: string;
    status: Variant_pending_dispatched_delivered_confirmed;
    createdAt: Time;
    agentName: string;
    customerMobile: string;
    updatedAt: Time;
    totalAmount: number;
    items: Array<OrderItem>;
    agentMobile: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n5(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        agentName: value.agentName,
        customerMobile: value.customerMobile,
        updatedAt: value.updatedAt,
        totalAmount: value.totalAmount,
        items: value.items,
        agentMobile: value.agentMobile
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: {
        closed: null;
    } | {
        in_progress: null;
    } | {
        open: null;
    };
    assignedAgentName: string;
    assignedAgentMobile: string;
    createdAt: _Time;
    customerMobile: string;
    description: string;
    updatedAt: _Time;
}): {
    id: bigint;
    customerName: string;
    status: Variant_closed_in_progress_open;
    assignedAgentName: string;
    assignedAgentMobile: string;
    createdAt: Time;
    customerMobile: string;
    description: string;
    updatedAt: Time;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n8(_uploadFile, _downloadFile, value.status),
        assignedAgentName: value.assignedAgentName,
        assignedAgentMobile: value.assignedAgentMobile,
        createdAt: value.createdAt,
        customerMobile: value.customerMobile,
        description: value.description,
        updatedAt: value.updatedAt
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    dispatched: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): Variant_pending_dispatched_delivered_confirmed {
    return "pending" in value ? Variant_pending_dispatched_delivered_confirmed.pending : "dispatched" in value ? Variant_pending_dispatched_delivered_confirmed.dispatched : "delivered" in value ? Variant_pending_dispatched_delivered_confirmed.delivered : "confirmed" in value ? Variant_pending_dispatched_delivered_confirmed.confirmed : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    in_progress: null;
} | {
    open: null;
}): Variant_closed_in_progress_open {
    return "closed" in value ? Variant_closed_in_progress_open.closed : "in_progress" in value ? Variant_closed_in_progress_open.in_progress : "open" in value ? Variant_closed_in_progress_open.open : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceRequest>): Array<ServiceRequest> {
    return value.map((x)=>from_candid_ServiceRequest_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n3(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_dispatched_delivered_confirmed): {
    pending: null;
} | {
    dispatched: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == Variant_pending_dispatched_delivered_confirmed.pending ? {
        pending: null
    } : value == Variant_pending_dispatched_delivered_confirmed.dispatched ? {
        dispatched: null
    } : value == Variant_pending_dispatched_delivered_confirmed.delivered ? {
        delivered: null
    } : value == Variant_pending_dispatched_delivered_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_closed_in_progress_open): {
    closed: null;
} | {
    in_progress: null;
} | {
    open: null;
} {
    return value == Variant_closed_in_progress_open.closed ? {
        closed: null
    } : value == Variant_closed_in_progress_open.in_progress ? {
        in_progress: null
    } : value == Variant_closed_in_progress_open.open ? {
        open: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
